name: compile-tex
run-name: Compiling Tex Files
on: [push]
jobs:
  compile-tex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install texlive texlive-publishers texlive-science latexmk cm-super
      - run: make

      - name: Archive pdfs
        uses: actions/upload-artifact@v4
        with:
          name: output_pdfs
          path: build/*.pdf

